### ISSUE TITLE
Social Network base on real community users

### ISSUE THREAD

**Issue by Qolzam** [Qolzam/react-social-network#116]
@Qolzam I am ready to be long term contributor and my vision is that this community is used by real users (Yes, I would be happy to use new technologies and use AI/ML, etc). So I feel we should also try to get the real users so that they can use it and keep this community active. The community can be for developers or musician or players or any specific community of the close group. A good example can be  'Spectrum' which is community exclusive for developers. 

I agree with you that we should create milestones to launch the beta version for real users (You can decide which community can be on this platform). I feel if there are uses on the community then we shall get feedback and we shall be building solutions based on their requirements. 

What do you think about this?

_Originally posted by @ipragmatechadmin in https://github.com/red-gold/social-firebase/issues/1#issuecomment-492685349_

**Comment by Qolzam** [comment]
@ipragmatechadmin I couldn’t agree with you more, community is the point. I have thought about a community of developers who can have technical view too. Who are using this project, willing to help us expanding the project. Therefore we need a design to able people add their custom extensions.
We focus on platform itself. We can think of [slack app](https://slack.com/apps) idea. Meaning if there is any requirement, user will make the solution. 

Please share with me if you have better idea.

**Comment by ipragmatechadmin** [comment]
@Qolzam Completely agree with you. The platform should be flexible enough so that if someone wants to add the extension or module then they should be able to do it. But we need to plan a live environment where people can actually use the platform. Do you have a feature lists for the stable version? Maybe we can work on it and plan a release? So you think developers community shall be our target? just like https://spectrum.chat/ ?

Lastly, can you make me a contributor to this project so that we can fix some of the obvious issues and try to have a stable version?

**Comment by Qolzam** [comment]
@ipragmatechadmin Generally for stable version following features should be avialable:

- [x] OAuth (login by other social networks).
- [x] Search in post and users ( It's done in new v0.7.0 using Algolia)
- [x] Chat ( It's done in new v0.7.0 )
- [x] Posts
- [x] Comment on post
- [x] Follow People
- [x] Profile
- [x] Share post ( Only as a link or to post in other social networks
- [x] Main Stream page
- [x] Like posts
- [x] Permission for post ( It's done in new v0.7.0 )
- [x] Photo albums ( It's done in new v0.7.0 )
- [x] Post photo
- [x] Post video
They are some important feature supposed to be. 
It's better that I have your feedback about problem or required feature too. Then we will set target for release. Can you share with me your idea?

Thanks!

**Comment by ipragmatechadmin** [comment]
@Qolzam Thanks for sharing the list. I feel we should have some feature where user can discuss the idea/problem. I was hoping to have a group(e.g. Cryptocurrency) feature where people shall join it and discuss the ideas/issue. What are your thoughts about it?

Here is a list of issues that we found (Should we create an issue for each?):

Enhancement & Fixes:

1.) Profile:

	Need to enhance :

		1. We can use the direct image at image upload without waiting for the response and update it in background

		2. Also, the uploaded image size is not the same as the need to correct them

		3. Album data is not stored persistent and after religion data not coming

 	 Sometimes not working well:

	 	1. Choose image banner cover pic not working

		2. If we have already uploaded the pic then pic can’t be uploaded to the app

		

	

2.) Header:

 	Need to enhance :

		1. My account selectable but not working, we can fix by showing the account info with editable button activation

 3.) Home :

 	Need to enhance : 

		1. Feeds are not  persistent need to make them persist

		2. Post image -> then like -> and after that -> goto comments -> there is white page whole app is not responding 



 4.) Help : 

 	Not implemented yet , need to implements



 5.) Send feedback : 

 		Need to enhance :

			1. As we post any feedback the round circle revolving not come to end but after another click on send feedback it shows “We appreciate your kind support as always ;)” 



6.) Setting : 


	1. Change password :

		Need to enhance:

			1. We change the password and click at the submit then no msg of update password show, we can show the msg and redirect to the home

**Comment by Qolzam** [comment]
@ipragmatechadmin Thanks for your idea and investigation on project :). I would appreciate it if you could create issue for each to discuss on as an issue.

Thanks again!

**Comment by Abhiranjanchaurasia** [comment]
@Qolzam Thanks for your appreciate, as we discuss above there is need to enhance at the profile image uploading :
1. We can use the direct image at image upload without waiting for the response and update it in background
To generate issue follow :  goto profile -> select edit profile -> select photo upload -> then input the photo -> here we can use the direct image uploading in same manner  as image uploads at the time of album creation instead of showing loading text with red background.
Image uploading screen at profile:
![Screenshot 2019-05-27 at 6 55 37 PM](https://user-images.githubusercontent.com/47344994/58424205-91cb5000-80b4-11e9-840f-9e545d2391d6.png)
Image uploading screen at Album:
![Screenshot 2019-05-27 at 6 58 47 PM](https://user-images.githubusercontent.com/47344994/58424325-cb9c5680-80b4-11e9-8d67-d2ddb761d256.png)
 Also we discuss about size of profile image at time of uploading screen:
2. Also, the uploaded image size is not the same as the need to correct them
please look at the image uploaded and upload image button, both are with  different frame. It will look pity well if they have same size.

**Comment by Abhiranjanchaurasia** [comment]
@Qolzam we also discuss the data persistency of the album and the feeds which are not supported by the app:
1. Album data is not stored persistent and after religion data not coming
when we refresh the app data totally remove from the app
Before Refreshing the App image of album is
![beforeRefAlbum](https://user-images.githubusercontent.com/47344994/58425722-297e6d80-80b8-11e9-81c3-15dbd3f383ad.png)
After Refreshing the App the App looks like:
![AfterRefAlbum](https://user-images.githubusercontent.com/47344994/58425752-46b33c00-80b8-11e9-957b-dc390d6d7977.png)

2. Feeds are not  persistent need to make them persist
Before Refreshing the app:
![BeforeRefFeeds](https://user-images.githubusercontent.com/47344994/58425801-6c404580-80b8-11e9-86e1-ffef50ead1bb.png)
After Refreshing the App:
![AfterRefFeeds](https://user-images.githubusercontent.com/47344994/58425821-78c49e00-80b8-11e9-86e4-09453ef46eae.png)

**Comment by Abhiranjanchaurasia** [comment]
@Qolzam  we also discuss about the banner image issue, actually banner image uploading successfully but when we set the banner image then it will not show the image for the cropping or edit,
it shows the blank space there.
1. Choose image banner cover pic not working
After uploading the banner image:
![Screenshot 2019-05-27 at 7 55 12 PM](https://user-images.githubusercontent.com/47344994/58426372-e624fe80-80b9-11e9-9782-388a8179f2d5.png)
When we select the set banner image button:
![Screenshot 2019-05-27 at 7 55 24 PM](https://user-images.githubusercontent.com/47344994/58426403-f89f3800-80b9-11e9-94d1-5b5cc7c7b566.png)

**Comment by Abhiranjanchaurasia** [comment]
@Qolzam we have also discuss about the selecting the my account doen't showing the edit profile, it may be pity well if it shows the edit profile.
 My account selectable but not working, we can fix by showing the account info with editable button activation
![Screenshot 2019-05-27 at 8 03 34 PM](https://user-images.githubusercontent.com/47344994/58426616-a7dc0f00-80ba-11e9-903d-a890d9aa22f6.png)

**Comment by Abhiranjanchaurasia** [comment]
@Qolzam we have also discussed the white screen appearing postimng comments  just after the recently posted feeds (feeds may be a image)
2. Post image -> then like -> and after that -> goto comments -> there is white page whole app is not responding 
As we click the comment button it shows:
![Screenshot 2019-05-27 at 8 07 21 PM](https://user-images.githubusercontent.com/47344994/58426904-8fb8bf80-80bb-11e9-81f3-b8948121bc48.png)
And After waiting sometimes it shows:
![Screenshot 2019-05-27 at 8 07 08 PM](https://user-images.githubusercontent.com/47344994/58426923-a2cb8f80-80bb-11e9-93fe-d173b67a1dbd.png)

**Comment by Abhiranjanchaurasia** [comment]
@Qolzam we also discussed about the send feedback, as we select the send feedback and select any feelings the it remain showing the constant screen .
1. As we post any feedback the round circle revolving not come to end but after another click on send feedback it shows “We appreciate your kind support as always ;)” 
Screenshot is:
![Screenshot 2019-05-27 at 8 13 56 PM](https://user-images.githubusercontent.com/47344994/58427110-40bf5a00-80bc-11e9-9428-715fd2a5f6f4.png)
After refreshing the app look better.

**Comment by kapilip** [comment]
@Qolzam We have written a blog for v0.7 installation. Can you take a look and let us know your thoughts? After you approve it then we shall update this information on the Readme file.

**Comment by Qolzam** [comment]
Hello @kapilip , Great! How I can access the blog? By the way I think we need to fix the issues first. I don't think it is ready for other users as they face with some problems. How is your idea about this?

**Comment by kapilip** [comment]
Hi @Qolzam, Oops , I forgot to mention the link for the blog. https://www.ipragmatech.com/how-effortlessly-create-free-social-media-app-react-nodejs/. 
Yes, I agree that we need to fix the issues. We are fixing the issues and hope to fix most of the issues by next week.

**Comment by Qolzam** [comment]
@kapilip I do appreciate what you have done. 👍 
Just to make the article perfect there are some points. I believe if you go through article to install the project you will face some issues such as Enabling Firestore and some security cautions when they add configuration like in `.firebaserc` file they should not publish in public repository. And about the last part I did not get why after user signup, they should get verification code from DB! which is not realistic. We have `email and SMS` verification feature.

I am very looking forward to checking improvements, Thanks!  :)

**Comment by Abhiranjanchaurasia** [comment]
Hello Amir,

I understand your concerns. My thoughts on these points are as follows -

1) To Enable Firestore & Configuration stuff we already added a link to
official documents there. We need to make them look more like links, like
underline them.
2) To get the verification code from DB :  To get the verification code via
email and SMS there is a need to follow the steps as below:
 go to firebase project -> select authentication ->set teplate-> you got
following options to set
 a) Email address verification
 b) password reset
 c) Email address change
 d) SMTP Setting
e) SMS Verification
if the user can not be enabled and set the template, verification code does
not receive the user, in this case, the user may receive it from the DB and
follow some steps and get the verification code easily.
That's why we mention these steps to get the verification code from the DB.
The verification code from DB will be last resort in case the user is
unable to access email and SMS.

Thanks & Regards,
Abbiranjan Chaurasia | Software Developer (iOS),
iPragmatech <http://www.ipragmatech.com/> Solutions
<http://www.ipragmatech.com/>
phone 91-120-4284907 | Skype abhiranjan101_2
Tweet iPragmatech <https://twitter.com/iPragmatech>  | Facebook iPragmatech
<http://www.facebook.com/ipragmatech>
Magento Mobile app
<https://play.google.com/store/apps/details?id=com.ipragmatech.magentoapi&hl=en>
 | Woocommerce Mobile app
<https://play.google.com/store/apps/details?id=com.ipragmatech.woocommerce&hl=en>
 | Socialengine Mobile app
<https://play.google.com/store/apps/details?id=com.ipragmatech.socialengineapi&hl=en>
