### ISSUE TITLE
[Bug] Banner doesn't show the image

### ISSUE THREAD

**Issue by Qolzam** [Qolzam/react-social-network#119]
@Qolzam  we also discuss about the banner image issue, actually banner image uploading successfully but when we set the banner image then it will not show the image for the cropping or edit,
it shows the blank space there.
1. Choose image banner cover pic not working
After uploading the banner image:
![Screenshot 2019-05-27 at 7 55 12 PM](https://user-images.githubusercontent.com/47344994/58426372-e624fe80-80b9-11e9-9782-388a8179f2d5.png)
When we select the set banner image button:
![Screenshot 2019-05-27 at 7 55 24 PM](https://user-images.githubusercontent.com/47344994/58426403-f89f3800-80b9-11e9-94d1-5b5cc7c7b566.png)

_Originally posted by @Abhiranjanchaurasia in https://github.com/red-gold/react-social-network/issues/116#issuecomment-496231419_

**Comment by Abhiranjanchaurasia** [comment]
@Qolzam we have discussed the bug on the banner image update :
 => Actually banner image uploading successfully but when we set the banner image then it will not show the image for the cropping or edit, it shows the blank space there.
The bug has been fixed by updating the cors implementation in the project, please make sure and merge the code.
