### ISSUE TITLE
mobile app

### ISSUE THREAD

**Issue by bayareabear** [Qolzam/react-social-network#128]
If I want to convert react-social to an iOS or android app, how to do it?

**Comment by Qolzam** [comment]
Can you explain more about your use case?

**Comment by bayareabear** [comment]
so after you make an web app, you want to acquire more users, eventually, you want to go mobile. After all, social app should go mobile, so why not make mobile app first?

**Comment by Qolzam** [comment]
You are absolutely right. Because this project start with different target at the beginning. 

Time is narrow and I have to take care of both backend and frontend. So I mainly worked on backend continuing with the same ReactJs frontend (Though I tried to build [mobile app](https://github.com/Qolzam/react-mobile-social)). 
For now I am trying to work on making the setup easier for users and writing document. 
Anyway I need to make time for mobile app which make the project perfect.

**Comment by Qolzam** [comment]
Close with #131.
