### ISSUE TITLE
[discussion] TypeScript or Create react app

### ISSUE THREAD

**Issue by QuantumInformation** [Qolzam/react-social-network#15]
Would  TypeScript or Create react app be of interest? With TypeScript you don't need to worry about proptypes.

**Comment by QuantumInformation** [comment]
There is also https://github.com/wmonk/create-react-app-typescript

**Comment by Qolzam** [comment]
I really appreciate your awesome suggestion. Indeed it's what I love to do .First as a .NET fan I greatly agree moving to TS. There are lots of cool features that I love such as typesafe programming, strong-typing, interface, generic stuff and so on. As a result we have cleaner, more reliable and maintainable code. I need to move to TS because this project is bigger than what I thought first so it would be hard to manage in the future.

**Comment by toyeebgodo** [comment]
@QuantumInformation , I salute, respect, and admire your level of proficiency. I have an amateur and selfish concern about the introduction of Typescript and the discounting of Proptypes even though I have read your well founded opinions above. I have spent over 1200 hours in the last five months learning Javascript, React, GraphQL, and Apollo and I am just finding my feet. This project would have been down my alley if not for the typescript. It is so sad for an amateur and newbie like me who is on the verge of being bankrupt when it comes to time that I have to go pick up Typescript knowledge in order to understand and work with a React Project. @Qolzam, can I get the old codes in which you used Proptypes? Guys, please don't be annoyed at this beginner and amateur who knows not of what he is saying.

**Comment by Qolzam** [comment]
@toyeebgodo  Thanks for using React Social Network. I agree with what you said. In the beginning I also had this attitude to follow javascript as whole the things for this project and most of the new users come back to javascript. However as the project growing I couldn't control changing structure and many bugs happened in runtime. Sure there are some good structures to implement javascript project and good design patter not to change the structure. However, for implementing some ideas and to make the project more flexible javascript doesn't make me happy. Moreover developing in typescript is much faster and cleaner than javascript. The next version of this project migrate to typescript with many new awesome stuff, cleaner code, high performance, with AWS and Firebase back-end, easy deploying and `CLI` to modify project easily. However, this project support `.jsx` and `.js` file to so if you want you can add your javascript file easily so `Webpack` compile it for you. On the whole I have another idea too. I could open another repository for javascript user with tutorial purpose.  How about this Idea?

**Comment by Qolzam** [comment]
I've created [js-react-social-tutorial](https://github.com/Qolzam/js-react-social-tutorial) repository. If you have any ideas or reporting bug I would be happy sharing with us.

**Comment by QuantumInformation** [comment]
@Qolzam I doubt there is much worth in splitting the work over 2 repos, as it will dilute the effort needed to maintain 1 good version.

@toyeebgodo Typescript is simply a superset of javascript, there's not much extra to learn apart from typing.

**Comment by Qolzam** [comment]
@QuantumInformation sure we don't work on two repository. Let me make it clearer that it's only for education or tutorial purpose. And new repository just for the users who are using javascript to run react. As this project migrate to typescript completely I think it's worth at least we have a backup of javascript codes so some users can develop themselves and contribute their ideas. Then they can move to the main project and learn about typescript more. It's like an encouragement in my idea.

**Comment by toyeebgodo** [comment]
@Qolzam, I'm so appreciative of your unusual kindness. Thank you so much for adding this repository https://github.com/Qolzam/js-react-social-tutorial for educational reasons; I am in total support. You just made my life easier as a learner. @QuantumInformation, I see and empathize with your viewpoint too, however, please allow him keep the JS repo for the sake of all newbies out there . In all seriousness, though, I am going to take up your advice on Typescript being simple to learn and put it on my list of next todos. Thank you so much to both of you.

**Comment by toyeebgodo** [comment]
@Qolzam your point, "However, for implementing some ideas and to make the project more flexible javascript doesn't make me happy. Moreover developing in typescript is much faster and cleaner than javascript. The next version of this project migrate to typescript with many new awesome stuff, cleaner code, high performance, with AWS and Firebase back-end, easy deploying and CLI to modify project easily. " is clearly taken by me.

@QuantumInformation, your point s are also clearly taken. Muchas gracias.

**Comment by Qolzam** [comment]
Moved on create-react-app and typescript merged.
