### ISSUE TITLE
environment.dev.ts (5,13): " should be '

### ISSUE THREAD

**Issue by indokely** [Qolzam/react-social-network#52]
Hello , I am getting below error... Please help

ts-loader: Using typescript@2.8.3 and C:\Users\handm\Dropbox\MundelProjects\React\GitProjects\react-social-network\tsconfig.json

Could not find implementations for the following rules specified in the configuration:
    ter-indent
    no-extra-boolean-cast
Try upgrading TSLint and/or ensuring that you have all necessary custom rules installed.
If TSLint was recently upgraded, you may have old rules configured which need to be cleaned up.
Failed to compile.

C:/Users/handm/Dropbox/MundelProjects/React/GitProjects/react-social-network/src/config/environment.dev.ts
(5,13): " should be '

**Comment by Qolzam** [comment]
Hello @indokely, seems when you copy/paste firebase configuration, you forget to replace `"` with `'` . Following [tsling rules](https://palantir.github.io/tslint/rules/) in this project you only can use `'` instead of `"`. If you are not happy with that rules you can try change the rules in [tslint.json](https://github.com/Qolzam/react-social-network/blob/next/tslint.json) file in project root folder.
Let me know if you have any issue.
