### ISSUE TITLE
Do I need the backend code?

### ISSUE THREAD

**Issue by easonychang** [Qolzam/react-social-network#57]
I am using react-social-network, and it seems like it's good standing alone, after connecting to a cloud firestore database. But someone else said this repo cannot be used stand alone unless pairing with the  https://github.com/Qolzam/firestore-social-backend repo.

**Comment by Qolzam** [comment]
Hello @easonychang , thanks for pointing this issue. I can tell you is stand alone repo why? because whole the services are using interfaces  from [core services](https://github.com/Qolzam/react-social-network/tree/next/src/core/services). It means you are able to implement your own service and [inject to the container](https://github.com/Qolzam/react-social-network/blob/next/src/data/firestoreClient/dependecyRegisterar.ts). Sure there are some challenge such as stream data which has it's own solution. I have implemented  AWS and ASP.NET Core some how but as it takes so much time it's developing so slowly.
If you are interested in any kind of backend to implement for this repository, I am happy to help so we can make it faster.

**Comment by easonychang** [comment]
So I think my understanding was that this repo is stand alone, and I don't really need the firestore-social-backend repo along with it to be able to interact with the database that I have configured on firebase.

**Comment by Qolzam** [comment]
Sure at least you need to have a back-end and database to store the data. However for [firestore-social-backend](https://github.com/Qolzam/firestore-social-backend) is only configuration using [Firestore Database](https://firebase.google.com/docs/firestore) not really huge backend to manipulate the data. Almost manipulating data is done on this repository as a [Firestore Data Client](https://github.com/Qolzam/react-social-network/tree/next/src/data/firestoreClient). With this you have kind of [Serverless Architecture](https://martinfowler.com/articles/serverless.html).
Hope it's helpful. Let me know if any question. Thanks!

**Comment by easonychang** [comment]
I see. I followed the instructions on your medium post, was able to configure it with firestore even without firestore-social-backend repo. Which was why I was a little bit confused of why I needed the backend repo to have the app running.

**Comment by Qolzam** [comment]
I am going to close this issue. Let me know if any issue. Thanks!
